# Add your code below
version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "task-manager-app"
    ports:
      - 8000:8000
    networks:
      - task-manager-network
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
  mongodb:
    image: mongo:6.0.8
    container_name: "task-manager-db"
    ports:
      - 27027:27017
    networks:
      - task-manager-network
    volumes:
      - task-manager-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env

networks:
  task-manager-network:
volumes:
  task-manager-data: